//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания «Store» – ведущая национальная сеть магазинов электробытовой и компьютерной техники Казахстана.
        ///    Компания была образована в 2002 году в Алматы и является на 100% казахстанской. Сегодня сеть «Store» включает 59 магазинов общей торговой площадью более 71 000 кв. м в 26-и городах республики. Компания, продолжающая свое активное развитие, открыта для всего нового и прогрессивного..
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лидерство компании «Store» среди конкурентов обусловлено несколькими факторами. Прежде всего, компания ориентирована на Клиента и предлагает максимально возможный ассортимент электроники и бытовой техники всех ценовых классов. Благодаря наиболее привлекательным ценам «Store» делает электробытовую и компьютерную технику доступной для всех слоев населения. Компания динамично развивается, применяет передовые торговые технологии и уделяет особое внимание профессиональному уровню своих сотрудников. Продуманный с [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модельный ряд электробытовой и компьютерной техники, предлагаемый компанией, насчитывает 10 тысяч наименований и охватывает все возможные типы продукции, в том числе:
        ///    ∙ Аудио- и видеотехника
        ///    ∙ Бытовая и встраиваемая техника
        ///    ∙ Компьютеры и периферийная техника
        ///    ∙ Игровые консоли и приставки
        ///    ∙ Офисная техника
        ///    ∙ Климатическая техника
        ///    ∙ Автомобильная аудиотехника
        ///    ∙ Мобильные телефоны и аксессуары
        ///    ∙ Фотоаппараты
        ///    ∙ Медианосители
        ///    ∙ Посуда и бытовая химия.
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В торговый портфель «Store» входят ведущие мировые марки: Sony, Panasonic, Samsung, LG, Daewoo, Apple, HTC, Philips, Nokia, Canon, Nikon, Fujitsu, Bosch, Siemens, Electrolux, Indesit, Hotpoint-Ariston, Elica, Gorenje, Hansa, Zigmund &amp; Shtain, Zanussi, Whirlpool, Beko, Termex, Moulinex, Tefal, Rowenta и др..
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазины «Store» спроектированы с учетом новейших торговых технологий и полностью отвечают мировым стандартам обслуживания покупателей. Единая концепция магазинов компании была создана в 2004 году совместно с ведущей европейской консалтинговой компанией Umdasch, работающей с крупнейшими торговыми сетями Европы. В каждом магазине «Store» предусмотрены эмоциональные и ценовые зоны, четкая и понятная система информирования о товарах и услугах, легко читаемое направление движения по торговому залу, удобный дост [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string About5 {
            get {
                return ResourceManager.GetString("About5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магазины «Store» спроектированы с учетом новейших торговых технологий и полностью отвечают мировым стандартам обслуживания покупателей. Единая концепция магазинов компании была создана в 2004 году совместно с ведущей европейской консалтинговой компанией Umdasch, работающей с крупнейшими торговыми сетями Европы. В каждом магазине «Store» предусмотрены эмоциональные и ценовые зоны, четкая и понятная система информирования о товарах и услугах, легко читаемое направление движения по торговому залу, удобный дост [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string About6 {
            get {
                return ResourceManager.GetString("About6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про нас.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзину.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзину добавлен товар:.
        /// </summary>
        public static string AddToCartProduct {
            get {
                return ResourceManager.GetString("AddToCartProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объем встроенной памяти, Гб.
        /// </summary>
        public static string BuildMemory {
            get {
                return ResourceManager.GetString("BuildMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камера(mpx).
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер карточки.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите страну.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо, что вы с нами! Мы делаем все, чтобы вы оценили наш уровень сервиса и получали удовольствие от покупок. Мы развиваем сервисы и работаем с вашими пожеланиями, помогая найти то, что нужно именно вам..
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есть вопросы? Предложения по нашей работе?
        ///        Звоните по телефону 8 800 080 1111 (звонок по Казахстану бесплатный),
        ///        Или пишите на.
        /// </summary>
        public static string Contact2 {
            get {
                return ResourceManager.GetString("Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для покупателей.
        /// </summary>
        public static string Contact3 {
            get {
                return ResourceManager.GetString("Contact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для соискателей.
        /// </summary>
        public static string Contact4 {
            get {
                return ResourceManager.GetString("Contact4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытые вакансии головного офиса, сервисных центров и розничных магазинов опубликованы в разделе &quot;Карьера&quot;.
        /// </summary>
        public static string Contact5 {
            get {
                return ResourceManager.GetString("Contact5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить покупки.
        /// </summary>
        public static string ContinueShop {
            get {
                return ResourceManager.GetString("ContinueShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказчик.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забота о клиентах.
        /// </summary>
        public static string CustomerCare {
            get {
                return ResourceManager.GetString("CustomerCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата заказа.
        /// </summary>
        public static string DataOrder {
            get {
                return ResourceManager.GetString("DataOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата поступление продукта.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисплей.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти в корзину.
        /// </summary>
        public static string GoToShopCart {
            get {
                return ResourceManager.GetString("GoToShopCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жесткий диск, Гб.
        /// </summary>
        public static string HardDisk {
            get {
                return ResourceManager.GetString("HardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня мы познакомимся с ноутбуком, на принадлежность к классу бюджетных у которого указывает только цена. У него оригинальный дизайн в стиле ультрабука, качественное исполнение и нет оптического привода. Наклейка на корпусе “Pentium inside” вызывает ностальгическое чувство. Сейчас Pentium – доступные, но достаточно производительные процессоры для ежедневных задач..
        /// </summary>
        public static string Index1 {
            get {
                return ResourceManager.GetString("Index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Через несколько недель стартует выставка MWC в Барселоне и нам покажут много интересных новинок. Конечно, мы все в основном ждем Galaxy S6 и Galaxy S6 Edge. Напомню, что практически каждый флагман Samsung, да и просто любой смартфон компании на сегодняшний день выпускается с предустановленными приложениями (как собственные, так и от сторонних разработчиков). По сути, всех изначальных возможностей хватает на все случаи жизни..
        /// </summary>
        public static string Index2 {
            get {
                return ResourceManager.GetString("Index2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласно неофициальным данным, Samsung Galaxy S6 и S6 Edge будут оснащены восьмиядерным процессором Samsung Exynos 7, 3 Гбайт оперативной памяти, операционной системой Android 5.0.2 Lollipop «из коробки» и двумя камерами — на 20,7 и 5 мегапикселей. Bloomberg пишет, что оба новых телефона разрабатываются в рамках проекта Project Zero..
        /// </summary>
        public static string Index3 {
            get {
                return ResourceManager.GetString("Index3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самсунг Галакси Alpha — отличный смартфон, работающий на платформе Android с 8х-ядерным процессором Exynos 5 Octa 5430 1800Mhz, оснащенный Super AMOLED-дисплеем, отображающим до 16 млн. цветов, с диагональю 4.7&quot; и камерой на 12 Mpx. Оснащен аккумулятором на 1860 mAh Для коммуникации может предложить: WAP браузер, EDGE, HSDPA, HSPA, WiFi, LTE (4G), NFC, стерео Bluetooth, и, конечно, USB-порт. Для любителей музыки есть аудио выход на 3.5 мм..
        /// </summary>
        public static string Index4 {
            get {
                return ResourceManager.GetString("Index4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apple iPhone 6 получил 4,7-дюймовый IPS-дисплей с разрешением 1334 х 750 пикселей (326 ppi), контрастностью 1400:1, максимальной яркостью 500 нит и олеофобным покрытием. У Apple iPhone 6 Plus — 5,5-дюймовый IPS-дисплей с разрешением 1920 х 1080 пикселей (401 ppi), контрастностью 1300:1, максимальной яркостью 500 нит и олеофобным покрытием..
        /// </summary>
        public static string Index5 {
            get {
                return ResourceManager.GetString("Index5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apple iPhone 6 и iPhone 6 Plus оснащены обновленными 8-мегапиксельными камерами (размер пикселя — 1,5 микрона, диафрагма — f/2.2) с продвинутой системой автофокуса. Они могут снимать панорамные фотографии до 43 Мп и записывать Full HD видео с частотой 60 кадров в секунду, а также slo-mo видео с частотой до 240 кадров в секунду (720p). Основным отличием двух камер является система оптической стабилизации изображения в iPhone 6 Plus..
        /// </summary>
        public static string Index6 {
            get {
                return ResourceManager.GetString("Index6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список заказов.
        /// </summary>
        public static string ListOfOrders {
            get {
                return ResourceManager.GetString("ListOfOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная страница.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель.
        /// </summary>
        public static string Manufacturers {
            get {
                return ResourceManager.GetString("Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моя корзина.
        /// </summary>
        public static string MyShoppingCart {
            get {
                return ResourceManager.GetString("MyShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hовый продукт.
        /// </summary>
        public static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноутбуки.
        /// </summary>
        public static string Notebooks {
            get {
                return ResourceManager.GetString("Notebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операционная система.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наши события.
        /// </summary>
        public static string OurEvents {
            get {
                return ResourceManager.GetString("OurEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Победители акции &quot;Возьми свой золотой&quot;.
        /// </summary>
        public static string OurEvents1 {
            get {
                return ResourceManager.GetString("OurEvents1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рады сообщить итоги новогодней акции  в сети магазинов «Store» под названием «Возьми свой ЗОЛОТОЙ!» от Банка Хоум Кредит.В рамках акции были разыграны крупные денежные призы в эквиваленте сертификатов на покупку техники в национальной сети магазинов «Store» .
        ///        По итогам розыгрыша 30 клиентов получают по сертификату на 100 тысяч тенге и 5 клиентов – на 1 млн тенге!.
        /// </summary>
        public static string OurEvents2 {
            get {
                return ResourceManager.GetString("OurEvents2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sony дарит миллионы!.
        /// </summary>
        public static string OurEvents3 {
            get {
                return ResourceManager.GetString("OurEvents3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 14 февраля в магазине национальной сети «Store» в ТРЦ Mega Alma-Ata, состоялся праздничный розыгрыш одного миллиона тенге на покупку техники, в рамках акции «Sony дарит миллионы», проходившей совместно с компанией Sony.  Во время розыгрыша все пришедшие смогли увидеть яркие выступления танцоров и принять участие во всевозможных конкурсах и викторинах. Традиционно выбор победителя традиционно проходил методом генерации случайных чисел в режиме online.  Напомним, что акция проходила в период с 1 декабря 2014  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OurEvents4 {
            get {
                return ResourceManager.GetString("OurEvents4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А на машине лучше: ФИНАЛ!.
        /// </summary>
        public static string OurEvents5 {
            get {
                return ResourceManager.GetString("OurEvents5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 января в алматинском магазине национальной сети «Store», расположенном в ТРЦ «Прайм Плаза» состоялся красочный финал очередного этапа розыгрыша автомобилей в рамках акции «А на машине лучше!», которая проходила в сети магазинов электроники «Store». Розыгрыш привлек большое внимание жителей и гостей Южной столицы.
        ///        Всех пришедших ждала яркая и запоминающаяся  шоу - программа. Зрителей развлекали акробаты, танцоры и веселые мимы.  Все желающие могли принять участие в различных викторинах и шарадах, [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OurEvents6 {
            get {
                return ResourceManager.GetString("OurEvents6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платежная система осуществляется c WebMoney.
        /// </summary>
        public static string PaymentSystem {
            get {
                return ResourceManager.GetString("PaymentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мощность.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процессор.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукты.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформление покупки на сумму.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Quentity {
            get {
                return ResourceManager.GetString("Quentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оперативная память, Гб.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список покупок.
        /// </summary>
        public static string ShoppingList {
            get {
                return ResourceManager.GetString("ShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смартфоны.
        /// </summary>
        public static string SmartPhones {
            get {
                return ResourceManager.GetString("SmartPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма на WebMoney.
        /// </summary>
        public static string SumWeb {
            get {
                return ResourceManager.GetString("SumWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеть магазинов электроники «Store» заботится о каждом из своих клиентов. Наша главная цель – первоклассный сервис для всех..
        /// </summary>
        public static string Support1 {
            get {
                return ResourceManager.GetString("Support1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С 2012 года в компании «Store» работает отдел по заботе о клиентах.
        ///        Мы всегда готовы выслушать все пожелания и замечания относительно обслуживания и предоставления сервиса..
        /// </summary>
        public static string Support2 {
            get {
                return ResourceManager.GetString("Support2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные цели и задачи отдела:
        ///        - Работа с обращениями и жалобами;
        ///        - Предоставление первоклассного сервиса для каждого клиента;
        ///        - Проведение исследования «Тайный покупатель», для выявления слабых сторон;
        ///        - Ежедневная работа над улучшением качества обслуживания;.
        /// </summary>
        public static string Support3 {
            get {
                return ResourceManager.GetString("Support3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как с нами связаться?.
        /// </summary>
        public static string Support4 {
            get {
                return ResourceManager.GetString("Support4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C 08:00 до 24:00 ежедневно.
        /// </summary>
        public static string Support5 {
            get {
                return ResourceManager.GetString("Support5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кто заботится о Вас?.
        /// </summary>
        public static string Support6 {
            get {
                return ResourceManager.GetString("Support6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как мы заботимся о Вас?.
        /// </summary>
        public static string Support7 {
            get {
                return ResourceManager.GetString("Support7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические характеристики.
        /// </summary>
        public static string TechnicalParameters {
            get {
                return ResourceManager.GetString("TechnicalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техника.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернет магазин.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телевизоры.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип продукта.
        /// </summary>
        public static string TypeProduct {
            get {
                return ResourceManager.GetString("TypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видеокарта, Гб.
        /// </summary>
        public static string VideoCard {
            get {
                return ResourceManager.GetString("VideoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видеокарта.
        /// </summary>
        public static string VideoCardName {
            get {
                return ResourceManager.GetString("VideoCardName", resourceCulture);
            }
        }
    }
}
