//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Checks = new HashSet<Check>();
            this.Images = new HashSet<Image>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> refHardDisk { get; set; }
        public Nullable<int> RAM { get; set; }
        public Nullable<bool> WiFi { get; set; }
        public Nullable<int> refSystem { get; set; }
        public int refManufacturer { get; set; }
        public Nullable<int> refDisplay { get; set; }
        public Nullable<int> Bluetooth { get; set; }
        public Nullable<int> refCamera { get; set; }
        public Nullable<int> refVideoCard { get; set; }
        public int refDicProdType { get; set; }
        public string BuildMemory { get; set; }
        public Nullable<System.Guid> refProcessor { get; set; }
        public Nullable<int> refPower { get; set; }
    
        public virtual Camera Camera { get; set; }
        public virtual ICollection<Check> Checks { get; set; }
        public virtual DicProdType DicProdType { get; set; }
        public virtual HardDisk HardDisk { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual OperatingSystem OperatingSystem { get; set; }
        public virtual Power Power { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual VideoCard VideoCard { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual Product Product { get; set; }
        public virtual Display Display { get; set; }
    }
}
