//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor
    {
        public Processor()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public System.Guid Id { get; set; }
        public int refManufacturers { get; set; }
        public string Type { get; set; }
        public string ClockSpeed { get; set; }
        public int CountCore { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
    }
}
