//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCard
    {
        public VideoCard()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Memory { get; set; }
        public int refManufacturers { get; set; }
        public string GraphicsController { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
